# Debug
PRINT_DEBUG_GENERAL = False
PRINT_DEBUG_IP_INFO = True
PRINT_DEBUG_ERROR = True
PRINT_DEBUG_WIFI = True
PRINT_DEBUG_BT = True
PRINT_DEBUG_FIRESTORE = False
PRINT_DEBUG_MONITOR = False
PRINT_DEBUG_OPERATOR = True
PRINT_MQTT_COMMS = True
PRINT_DEBUG_MQTT = True